### ISSUE TITLE
Not able to install iata_codes module

### ISSUE THREAD

**Issue by pavankumar9** [Otetz/iata_codes#1]
Unable to install iata_codes package. Can you please look into this?

pavans-MacBook-Pro:pers pavan$ pip install iata_codes
Collecting iata_codes
  Could not find a version that satisfies the requirement iata_codes (from versions: )
No matching distribution found for iata_codes

Can you please let me know.

**Comment by Otetz** [comment]
Sorry, I don't check package when publish, my mistake.
